<?php

namespace Restomods\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuratedAutoDiscountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuratedAutoDiscountRepository extends \Doctrine\ORM\EntityRepository
{
}
