<?php

namespace Restomods\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends \Doctrine\ORM\EntityRepository
{
}
