<?php

namespace Restomods\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SweepstakesProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SweepstakesProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSweepstakesProducts($id = null, $type = null, $onlyActive = true){

        if ($type) {
            if ($onlyActive) {
                $query    = $this->createQueryBuilder( 'l' )
        		                 ->where( 'l.sweepstakes = :sweepstakes' )
        		                 ->andWhere( 'l.type = :type' )
                                 ->andWhere( 'l.active = true' )
        		                 ->setParameter( 'sweepstakes', $id )
                                 ->setParameter( 'type', $type )
        		                 ->orderBy( 'l.id', 'ASC' )
        		                 ->getQuery();
            } else {
                $query    = $this->createQueryBuilder( 'l' )
        		                 ->where( 'l.sweepstakes = :sweepstakes' )
        		                 ->andWhere( 'l.type = :type' )
        		                 ->setParameter( 'sweepstakes', $id )
                                 ->setParameter( 'type', $type )
        		                 ->orderBy( 'l.id', 'ASC' )
        		                 ->getQuery();
            }

    		return $query->getResult();
        } else {
            if ($onlyActive) {
                $query    = $this->createQueryBuilder( 'l' )
        		                 ->where( 'l.sweepstakes = :sweepstakes' )
                                 ->andWhere( 'l.active = true' )
        		                 ->setParameter( 'sweepstakes', $id )
        		                 ->orderBy( 'l.id', 'ASC' )
        		                 ->getQuery();
            } else {
                $query    = $this->createQueryBuilder( 'l' )
        		                 ->where( 'l.sweepstakes = :sweepstakes' )
        		                 ->setParameter( 'sweepstakes', $id )
        		                 ->orderBy( 'l.id', 'ASC' )
        		                 ->getQuery();
            }

    		return $query->getResult();
        }
    }
}
