<?php

namespace Restomods\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SweepstakesUserEntriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SweepstakesUserEntriesRepository extends EntityRepository
{
    public function getSweepstakesUserEntries($id = null, $uid = null){
        $em = $this->getEntityManager();
        $sql ="SELECT user_id, u.username, u.firstname, u.lastname, u.email, u.phone, sweepstakes_id, ROUND(SUM(s.entries)) AS points, SUM(CASE WHEN s.description = 'referrer' THEN 1 ELSE 0 END) referrer_count, s.created_at
               FROM `sweepstakes_user_entries` s
               JOIN `fos_user_user` u ON u.id = s.user_id
               WHERE active = 1 AND sweepstakes_id = ".$id." ".($uid ? ' AND user_id = '.$uid : null)."
               GROUP BY user_id
               ORDER BY s.created_at DESC
               ";
        $stm = $em->getConnection()->prepare($sql);
        $stm->execute();
        return $stm->fetchAll(\PDO::FETCH_ASSOC);
    }

    public function getAllSweepstakesUserEntries($id = null, $uid = null){
        $em = $this->getEntityManager();
        $sql ="SELECT user_id, sweepstakes_id, entries, description, s.created_at
               FROM `sweepstakes_user_entries` s
               JOIN `fos_user_user` u ON u.id = s.user_id
               WHERE active = 1 AND sweepstakes_id = ".$id." ".($uid ? ' AND user_id = '.$uid : null)."
               ORDER BY s.id ASC
               ";
        $stm = $em->getConnection()->prepare($sql);
        $stm->execute();
        return $stm->fetchAll(\PDO::FETCH_ASSOC);
    }
}
