<?php

namespace Restomods\ListingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserReferrerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReferrerRepository extends EntityRepository
{
}
